# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c201570508128432a2d451c06f7879cf019acd1647d4730f650eed359b3e0eb337956b2e48daf0e9731aa3075bf9a440f200510a762392a079d64812c5ec4c1

test:
  secret_key_base: f42efa86b08dd46438bb0f4bc844ce2261e5ac427c4fa8c3e04728715dab947acf1adedce0646f0ab0959cd864000fa6a97f72a32ac3538f97200770af850817

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
